import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { AppShell } from '@astryxdesign/core/AppShell'
import { Banner } from '@astryxdesign/core/Banner'
import { departments, displays, downloads, edition, eventFlyers, fairBoard, fairMission, generalRules, officialDepartmentContent, schedule, type Department } from './content/fairbook'
import './styles.css'
import './rules.css'

const asset = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`
const pdfFor = (d: Department) => d.source.split('/ ').at(-1)!
function Nav({go}:{go:(p:string)=>void}) { return <nav aria-label="Primary navigation"><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('exhibits')}>Exhibits</button>{edition.status==='confirmed'&&<button onClick={()=>go('schedule')}>Schedule</button>}<button onClick={()=>go('rules')}>General rules</button><button onClick={()=>go('print')}>Print downloads</button></nav> }
function Home({go}:{go:(p:string)=>void}) { return <><section className="hero"><img src={asset('assets/fair-hero.png')} alt="Illustrated county fair with barn, Ferris wheel, pumpkin, and flowers"/><div className="hero-copy"><p className="eyebrow">Benewah County, Idaho</p><h1>Make a little room for wonder.</h1><p>Everything you need to celebrate, exhibit, and share your best work at the county fair.</p><button className="primary" onClick={()=>go('exhibits')}>Explore exhibits <span>→</span></button></div></section><section className="welcome"><div><p className="eyebrow">A community tradition</p><h2>Bring what you’ve been growing, making, and dreaming about.</h2></div><p>{edition.mission} Browse departments online, then use the printable guides to prepare your entry.</p></section><section className="features"><div><h2>Find your place at the fair.</h2><button className="text-button" onClick={()=>go('exhibits')}>View all departments →</button></div><div className="feature-grid">{departments.slice(0,6).map(d=><button className="feature" key={d.slug} onClick={()=>go(`department/${d.slug}`)}><span>{d.icon}</span><strong>{d.name}</strong><small>{d.summary}</small></button>)}</div></section><section className="page"><p className="eyebrow">At the fair</p><h2>Events & food</h2>{eventFlyers.map(flyer=><article className="department-card" key={flyer.title}><div><h3>{flyer.title}</h3><p>{flyer.detail}</p></div></article>)}</section></> }
function Exhibits({go}:{go:(p:string)=>void}) { const [query,setQuery]=useState(new URLSearchParams(location.search).get('q')||''); const found=useMemo(()=>departments.filter(d=>JSON.stringify(d).toLowerCase().includes(query.toLowerCase())),[query]); const update=(value:string)=>{setQuery(value); history.replaceState(null,'',value?`?q=${encodeURIComponent(value)}`:location.pathname)}; return <section className="page"><p className="eyebrow">Exhibits directory</p><h1>Show us what you made.</h1><label className="search"><span>Search exhibits</span><input value={query} onChange={e=>update(e.target.value)} placeholder="Try “tomatoes” or “watercolor”" /></label><div className="directory">{found.map(d=><article key={d.slug} className="department-card"><span>{d.icon}</span><div><h2>{d.name}</h2><p>{d.summary}</p><button className="text-button" onClick={()=>go(`department/${d.slug}`)}>Open department →</button></div></article>)}</div>{!found.length&&<p role="status" className="empty">No exhibits matched “{query}”. Try a broader search.</p>}</section> }
function OfficialDepartmentDetails({slug}:{slug:string}) { const lines=officialDepartmentContent(slug).split('\n'); return <section className="official-details"><p className="eyebrow">Complete 2026 fairbook details</p>{lines.map((line,index)=>{const text=line.replace(/^#+\s*/, '').replace(/\*\*/g, '').replace(/^[-*]\s+/, '').trim(); if(!text||text==='---'||text==='<aside>'||text==='</aside>') return null; if(/^Class \d+\s*-/.test(text)) return <h3 key={index}>{text}</h3>; if(/^![\s\S]*\]\(/.test(text)) return null; return <p key={index}>{text}</p>})}</section> }
function DepartmentPage({department,go}:{department:Department;go:(p:string)=>void}) { return <section className="page detail"><button className="back" onClick={()=>go('exhibits')}>← All exhibits</button><p className="eyebrow">{department.source}</p><h1><span>{department.icon}</span>{department.name}</h1><p className="lede">{department.summary}</p><aside className="callout"><strong>Before you enter</strong>{department.rules.map(rule=><p key={rule}>{rule}</p>)}</aside><OfficialDepartmentDetails slug={department.slug}/><a className="primary" href={asset(`fairbook-pdfs/${pdfFor(department)}`)} target="_blank" rel="noreferrer">Open printable {department.name} guide ↗</a></section> }
function Rules(){return <section className="page rules"><p className="eyebrow">Fairbook essentials</p><h1>General rules</h1><p className="lede">These guidelines help make entries safe, fair, and ready for judging.</p><ol>{generalRules.map(x=><li key={x}>{x}</li>)}</ol><h2>Fair mission</h2><article className="department-card"><div><h3>{fairMission.title}</h3><p>{fairMission.text}</p></div></article><h2>Special exhibits & displays</h2><div className="display-grid">{displays.map(item=><article className="department-card" key={item.title}><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div><h2>Fair Board</h2><div className="board"><div><h3>Board members</h3>{fairBoard.members.map(person=><p key={person}>{person}</p>)}</div><div><h3>Secretary / Treasurer</h3><p>{fairBoard.secretaryTreasurer}</p><h3>Grounds & maintenance</h3>{fairBoard.groundsMaintenance.map(person=><p key={person}>{person}</p>)}</div><div><h3>County commissioners</h3>{fairBoard.commissioners.map(person=><p key={person}>{person}</p>)}</div><div><h3>Junior Show & Sale officers</h3>{fairBoard.juniorShowAndSale.map(person=><p key={person}>{person}</p>)}</div></div><p className="source-note">Editorial source: {edition.source}.</p></section>}
function Schedule(){const [category,setCategory]=useState('All');const shown=schedule.filter(item=>item.visible&&(category==='All'||item.category===category));const categories=['All',...new Set(schedule.filter(x=>x.visible).map(x=>x.category))];if(edition.status!=='confirmed')return <section className="page"><p className="eyebrow">Fair schedule</p><h1>Dates coming soon.</h1><p className="lede">The Fair Board has not yet confirmed annual dates, entry deadlines, or daily events. Please check back for the published schedule.</p></section>;return <section className="page"><p className="eyebrow">Fair schedule</p><h1>Plan your fair days.</h1><label className="search"><span>Filter events</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>{shown.map(event=><article className="department-card" key={`${event.date}-${event.title}`}><div><h2>{event.title}</h2><p>{[event.date,event.time,event.location].filter(Boolean).join(' · ')}</p></div></article>)}{!shown.length&&<p role="status" className="empty">No confirmed events are available for this filter.</p>}</section>}
function Print(){return <section className="page"><p className="eyebrow">Take it with you</p><h1>Printable fairbook guides</h1><p className="lede">The web guide is designed for easy reading. These original PDFs remain available for printing and full annual reference.</p><div className="downloads">{downloads.map(d=><a key={d.file} href={asset(`fairbook-pdfs/${d.file}`)} target="_blank" rel="noreferrer"><span>PDF</span><strong>{d.name}</strong><small>Open printable guide ↗</small></a>)}</div></section>}
function App(){ const [route,setRoute]=useState(()=>location.hash.slice(1)||'home'); const go=(p:string)=>{location.hash=p;setRoute(p);window.scrollTo({top:0})}; const dept=route.startsWith('department/')?departments.find(d=>d.slug===route.split('/')[1]):undefined; return <AppShell height="auto" contentPadding={0} variant="surface" banner={<Banner status="info" container="section" title="2026 fair dates" description={edition.announcement}/>} topNav={<header><button className="brand" onClick={()=>go('home')}><span>✦</span> Benewah County <b>FAIRBOOK</b></button><Nav go={go}/></header>} mobileNav={false}><>{dept?<DepartmentPage department={dept} go={go}/>:route==='exhibits'?<Exhibits go={go}/>:route==='schedule'?<Schedule/>:route==='rules'?<Rules/>:route==='print'?<Print/>:<Home go={go}/>}<footer><strong>Benewah County Fair</strong><span>2026 public guide · <button onClick={()=>go('print')}>Printable fairbook PDFs</button></span></footer></></AppShell> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
